# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92ffe55cd461978360b20949070f1cd56c7ee9423c8b183a65dc48db7954be8a91a873be518a91b17899e40375cd3688443e1ae3c168eaacf08a8a175ec6ab5

test:
  secret_key_base: 87f763293a198c5eae55926c106a45004b6e7da814c3f88d06fae3d28867983668ff3de88e2ea8997e4a929a17290cd7ef7aecaf5a15b10bbd418831050bb54d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
